energymanager/datahub_site/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from __future__ import unicode_literals

from django.conf.urls import patterns
from django.conf.urls import url

from . import views

urlpatterns = patterns(
    'energymanager.price_relay_site.views',
    url(r'^$',
        views.HomeView.as_view(),
        name='home'),
    url(r'^customer/(?P<customer_id>\d+)/$',
        views.CustomerView.as_view(),
        name='customer'),
    url(r'^choose-customer/$',
        views.ChooseCustomer.as_view(),
        name='choose-customer'),
    url(r'^connection/(?P<customer_id>\d+)/$',
        views.DatahubConnectionList.as_view(),
        name='connection-list'),
    url(r'^project/content/(?P<customer_id>\d+)/$',
        views.DatahubConnectionListContentView.as_view(),
        name='connection-list-content'),
    url(r'^connection/create/(?P<customer_id>\d+)/$',
        views.DatahubConnectionCreateView.as_view(),
        name='connection-create'),
    url(r'^connection/update/(?P<customer_id>\d+)/(?P<pk>\d+)/$',
        views.DatahubConnectionUpdateView.as_view(),
        name='connection-update'),
    url(r'^authorizations/',
        views.datahub_authorization_view,
        name='authorizations-view'),
)

gridplatform/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from __future__ import unicode_literals

from django.contrib import admin
import django.contrib.auth.models
from django.conf import settings
from django.conf.urls import include
from django.conf.urls import patterns
from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView
import djcelery.models

from gridplatform.utils.urls import restricted_url


js_info_dict = {
    'packages': (
        'legacy.website',
        'legacy.manage_devices',
        'legacy.manage_customers',
    ),
}


urlpatterns = patterns(
    '',
    (r'^i18n/', include('django.conf.urls.i18n')),
    (r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict),
    (r'^jserror/', include('gridplatform.jserror.urls')),
    url(r'^task_status/$',
        'gridplatform.utils.views.task_status',
        name='task_status'),
    url(r'^manage/customers/', include('legacy.manage_customers.urls')),
    url(r'^manage/agents/', include('legacy.setup_agents.urls')),
    url(r'^locations/', include('legacy.manage_locations.urls')),
    url(r'^groups/', include('legacy.manage_collections.urls')),
    url(r'^devices/', include('legacy.manage_devices.urls')),
    url(r'^measurementpoints/',
        include(
            'legacy.manage_measurementpoints.urls',
            namespace='manage_measurementpoints')),
    url(r'^overview/details/',
        include('legacy.display_measurementpoints.urls')),
    url(r'^overview/indexes/',
        include('legacy.display_indexes.urls')),
    url(r'^projects/', include('legacy.display_projects.urls')),
    url(r'^users/', include('legacy.manage_users.urls')),
    url(r'^widgets/', include('legacy.display_widgets.urls')),
    url(r'^userprofile/', include('legacy.edit_userprofile.urls')),
    url(r'^rules/', include('legacy.manage_rules.urls')),
    url(r'^indexes/', include('legacy.manage_indexes.urls')),
    url(r'^reports/', include('legacy.manage_reports.urls')),
    url(r'', include('legacy.website.urls')),
    url('^energy_use_reports/',
        include('legacy.energy_use_reports.urls')),
    url('^enpi_reports/',
        include('legacy.enpi_reports.urls')),
    url(r'^report_generators/', include('gridplatform.reports.urls')),
    url(r'^project_generators/', include('legacy.projects.urls')),
    url(r'^start/',
        include('energymanager.start_site.urls', namespace='start_site')),
    url(r'^user/', include('gridplatform.users.urls', namespace='users')),
    url(r'^Wibeee/', include('gridplatform.smilics.urls')),
    # Provider site
    restricted_url(
        r'^admin/',
        include('energymanager.provider_site.urls',
                namespace='provider_site'),
        permission='users.access_provider_site',
        requires_provider=True),
    restricted_url(
        r'^configuration/',
        include('energymanager.configuration_site.urls',
                namespace='configuration_site'),
        permission='users.access_provider_site',
        requires_provider=True),
    # LED Light site
    restricted_url(
        r'^led_light/',
        include('energymanager.led_light_site.urls',
                namespace='led_light_site'),
        permission='users.access_led_light_site'),

    # HACK to restrict project urls
    # TODO: Figure out why restricted_url doesn't work in app url files
    restricted_url(
        r'^led_light/',
        include('energymanager.led_light_site.restricted_urls',
                namespace='led_light_site_projects'),
        permission='users.access_led_light_site_projects'),

    # Access price_relay site
    restricted_url(
        r'^price_relay/',
        include('energymanager.price_relay_site.urls',
                namespace='price_relay_site'),
        permission='users.access_price_relay_site'),

    # Project site
    restricted_url(
        r'^escolite/',
        include('energymanager.project_site.urls',
                namespace='project_site'),
        permission='users.access_project_site'),

    # Datahub site
    restricted_url(
        r'^datahub/',
        include('energymanager.datahub_site.urls',
                namespace='datahub_site'),
        permission='users.access_datahub_site'),


    # REST API
    url(r'^api/current/',
        RedirectView.as_view(url=reverse_lazy('api:api-root')),
        name='api-current-version'),
    url(r'^api/v3/', include('gridplatform.api', namespace='api')),

)


admin.autodiscover()

admin.site.unregister(django.contrib.auth.models.User)

admin.site.unregister(djcelery.models.TaskState)
admin.site.unregister(djcelery.models.WorkerState)
admin.site.unregister(djcelery.models.IntervalSchedule)
admin.site.unregister(djcelery.models.CrontabSchedule)
admin.site.unregister(djcelery.models.PeriodicTask)


urlpatterns += patterns(
    '',
    restricted_url(
        r'^sysadmin/',
        include(admin.site.urls),
        requires_is_staff=True),
)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns(
        '',
        url(r'^__debug__/', include(debug_toolbar.urls)),
        url(r'^qunit/', include('django_qunit.urls')),
    )

wifiagent/wifiagent/urls.py
from django.conf.urls import url
#from django.contrib import admin

from wifiagent.relay import views

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'^receiver/$', views.receiver),
]

energymanager/datahub_site/models.py
from django.db import models

# Create your models here.

energymanager/datahub_site/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from __future__ import unicode_literals

import datetime
import calendar
import pycurl
import StringIO

from django.utils.translation import ugettext_lazy as _
from django.utils.translation import ugettext_lazy
from django import forms
from django.core.urlresolvers import reverse
from django.db.models.fields import BLANK_CHOICE_DASH
from django.http import HttpResponse
from django.conf import settings

from gridplatform.utils import generic_views
from gridplatform.utils import units
from gridplatform.utils.breadcrumbs import Breadcrumb
from gridplatform.utils.breadcrumbs import Breadcrumbs
from gridplatform.utils.views import ChooseCustomerBase
from gridplatform.utils.views import CustomerInKwargsMixin
from gridplatform.utils.views import CustomerListMixin
from gridplatform.utils.views import CustomerViewBase
from gridplatform.utils.views import HomeViewBase
from gridplatform.customers.models import Customer
from gridplatform.utils.forms import YearWeekPeriodForm
from gridplatform.utils.forms import this_week_initial_values
from gridplatform.datahub.models import DatahubConnection
from legacy.devices.models import PhysicalInput


class HomeView(HomeViewBase):
    def get_redirect_with_customer_url(self, customer_id):
        return reverse(
            'datahub_site:connection-list',
            kwargs={'customer_id': customer_id})

    def get_choose_customer_url(self):
        return reverse(
            'datahub_site:choose-customer')


class ChooseCustomer(ChooseCustomerBase):
    template_name = 'datahub_site/choose_customer.html'


class CustomerView(CustomerViewBase):
    def get_redirect_with_customer_url(self, customer_id):
        return reverse(
            'datahub_site:connection-list',
            kwargs={'customer_id': customer_id})


class DatahubConnectionList(CustomerListMixin, generic_views.TemplateView):
    template_name = 'datahub_site/datahub_connection_list.html'

    @staticmethod
    def build_breadcrumbs(customer_id):
        return Breadcrumbs() + Breadcrumb(
            _('Forbindelser'),
            reverse(
                'datahub_site:connection-list',
                kwargs={'customer_id': customer_id}))

    def get_breadcrumbs(self):
        return self.build_breadcrumbs(self._customer.id)


class DatahubConnectionListContentView(
        CustomerListMixin,
        generic_views.ListView):
    search_fields = ['customer_meter_number', ]
    sort_fields = ['customer_meter_number', ]
    model = DatahubConnection
    paginate_by = 100
    template_name = 'datahub_site/_datahub_connection_list_content.html'


class DatahubConnectionForm(forms.ModelForm):

    class Meta:
        model = DatahubConnection
        fields = (
            'customer_meter_number', 'meter'
        )


class DatahubConnectionCreateView(CustomerListMixin,
                                  generic_views.CreateView):
    model = DatahubConnection
    template_name = 'datahub_site/datahub_connection_form.html'
    form_class = DatahubConnectionForm

    def form_valid(self, form):
        form.instance.customer_id = self._customer.id
        meter = form.instance.meter
        input = PhysicalInput.objects.create(
            meter=meter,
            order=0,
            name_plain="Datahub",
            unit="milliwatt*hour",
            type=PhysicalInput.ELECTRICITY
        )

        form.instance.input = input

        response = super(DatahubConnectionCreateView, self).form_valid(form)
        return response

    def get_success_url(self):
        return reverse('datahub_site:connection-list',
                       kwargs={'customer_id':
                               self._customer.id})

    def get_cancel_url(self):
        return self.get_success_url()

    def get_breadcrumbs(self):
        return DatahubConnectionList.build_breadcrumbs(self._customer.id) + \
            Breadcrumb(_('Create connection'))


class DatahubConnectionUpdateView(CustomerListMixin,
                                  generic_views.UpdateView):
    model = DatahubConnection
    template_name = 'datahub_site/datahub_connection_form.html'
    fields = (
        'customer_meter_number',
    )

    def get_success_url(self):
        return reverse('datahub_site:connection-list',
                       kwargs={'customer_id':
                               self._customer.id})

    def get_cancel_url(self):
        return self.get_success_url()

    def get_breadcrumbs(self):
        return DatahubConnectionList.build_breadcrumbs(self._customer.id) + \
            Breadcrumb(self.object)


def datahub_authorization_view(request):
    b = StringIO.StringIO()
    c = pycurl.Curl()
    url = 'https://eloverblik.dk/api/authorizationsv2'
    c.setopt(pycurl.URL, url)
    c.setopt(pycurl.WRITEFUNCTION, b.write)
    c.setopt(pycurl.SSLKEY, settings.NETS_KEY_DIR + "/plainkey.pem")
    c.setopt(pycurl.SSLCERT, settings.NETS_KEY_DIR + "/crt.pem")
    c.perform()
    c.close()
    response_body = b.getvalue()
    return HttpResponse(response_body, content_type='application/json')

energymanager/datahub_site/templates/datahub_site/_datahub_connection_list_content.html
{% load i18n %}

{% if object_list %}
<table class="table table-striped table-bordered sorted" data-provides="rowlink">
  <thead>
    <th class="sorting" data-orderby="customer_meter_number">{% trans "Meter number" %}</th>
    <th></th>
  </thead>
  <tbody>
    {% for object in object_list %}
    <tr>
      <td>
        <a href="{% url "datahub_site:connection-update" customer_id=customer.id pk=object.id %}">{{ object.customer_meter_number }}</a>
      </td>
      <td>
        {% if not object.authorization_id %}
        <a href="#" data-number="{{ object.customer_meter_number }}" class="connect-datahub" onClick="checkAuthorization(event);">Tjek godkendelse</a>
        {% endif %}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% include "bootstrap/_pagination.html" %}
{% else %}
<span>{% trans "No datahub connections present." %}</span>
{% endif %}

energymanager/datahub_site/templates/datahub_site/_menu.html
{% load i18n %}

{% load bootstrap_tags %}

{% if customer %}
<ul class="nav main-menu">
   <li>
    <a href="{% url 'datahub_site:connection-list' customer_id=view.kwargs.customer_id %}">
      {% icon "bar-chart-o" %}<span class="hidden-sm text">{% trans 'Connections' %}</span>
    </a>
  </li>
</ul>
{% endif %}

energymanager/datahub_site/templates/datahub_site/_navbar.html
{% extends "bootstrap/_navbar_base.html" %}

{% load i18n %}
{% load bootstrap_tags %}

{% block home_url %}{% url 'datahub_site:home' %}{% endblock home_url %}
{% block title %}{% trans 'Datahub' %}{% endblock title %}

{% block menu_extra %}
{% include "utils/customer_selection_nav.html" %}
{% endblock menu_extra %}

energymanager/datahub_site/templates/datahub_site/base.html
{% extends "bootstrap/base.html" %}

{% load i18n %}

{% block page_title %}{% trans 'Datahub' %}{% endblock %}

{% block navbar %}
{% include "datahub_site/_navbar.html" %}
{% endblock %}

{% block sidebar %}
{% include "datahub_site/_menu.html" %}
{% endblock %}


{% block page_bottom %}
{% include "utils/customer_selection_modal.html" with urlname='datahub_site:customer' %}
{% include "datahub_site/datahub_authorization_modal.html" %}
{% endblock page_bottom %}

energymanager/datahub_site/templates/datahub_site/choose_customer.html
{% extends "datahub_site/base.html" %}

{% block page_js %}
<script type="text/javascript">
    jQuery(function() {
        $('#customer-select-modal').modal('show');
    });
</script>
{% endblock page_js %}

energymanager/datahub_site/templates/datahub_site/datahub_authorization_modal.html
{% load i18n %}

<div class="modal fade" id="dathub-authorization-modal" tabindex="-1" role="dialog" aria-labelledby="dathub-authorization-modal-label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="dathub-authorization-modal-label">{% trans 'Datahub Godkendelse' %}</h4>
      </div>
      <div class="modal-body">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">{% trans 'Ok' %}</button>
      </div>
    </div>
  </div>
</div>

energymanager/datahub_site/templates/datahub_site/datahub_connection_form.html
{% extends "datahub_site/base.html" %}
{% load i18n %}
{% load bootstrap_tags %}


{% block content %}
{% panel _("Datahub Connection Details") %}
{% bootstrap_form %}
{% form form %}
{% endbootstrap_form %}
{% endpanel %}
{% endblock %}

energymanager/datahub_site/templates/datahub_site/datahub_connection_list.html
{% extends "datahub_site/base.html" %}
{% load i18n %}
{% load pagination %}
{% load bootstrap_tags %}
{% block page_js %}
<script>
  var checkAuthorization = function(e) {
    e.stopPropagation();
    e.preventDefault();
    var target = $(event.target);
    var meterNumber = target.data('number');
    var url = '{% url "datahub_site:authorizations-view" %}';
    var data;
    var authorizationModal = $('#dathub-authorization-modal');
    $.get(url, function(response) {
      _(response).forEach(function(customer) {
        _(customer.ListOfMeteringPoints).forEach(function(meter) {
          if (meter.MeteringPointIdentification === meterNumber) {
            data={
              startDate: customer.StartDate,
              endDate: customer.EndDate,
              authorizationId: customer.Id
            }
          }
        });
      });
      if (data) {
        authorizationModal.find('.modal-body').html("<h2>Godkendt</h2>");
      } else {
        authorizationModal.find('.modal-body').html("<h2>Ikke godkendt</h2><p>Send anmodning om adgang</p>");
      }
      authorizationModal.modal("show");
    });
    return false;
  }

</script>
{% endblock page_js %}
{% block content %}
{% panel _("Datahub Connections") search=True %}
<a href="{% url "datahub_site:connection-create" customer_id=customer.id %}" title="{% trans 'Add' %}">
  {% icon "plus" %}
</a>
{% endpanelbuttons %}
<div class="content-loader" data-url="{% url "datahub_site:connection-list-content" customer_id=customer.id %}" data-orderby="customer_meter_number"></div>
{% endpanel %}

{% endblock %}