energymanager/led_light_site/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from __future__ import unicode_literals

from django.conf.urls import patterns
from django.conf.urls import url
from django.conf.urls import include

from gridplatform.utils.urls import restricted_url

from . import views

urlpatterns = patterns(
    'energymanager.led_light_view.views',
    url(r'^$',
        views.HomeView.as_view(),
        name='home'),
    url(r'^customer/(?P<customer_id>\d+)/$',
        views.CustomerView.as_view(),
        name='customer'),
    url(r'^choose-customer/$',
        views.ChooseCustomer.as_view(),
        name='choose-customer'),
    url(r'^(?P<customer_id>\d+)/dashboard/$',
        views.DashboardDetailView.as_view(),
        name='dashboard'),
)

gridplatform/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from __future__ import unicode_literals

from django.contrib import admin
import django.contrib.auth.models
from django.conf import settings
from django.conf.urls import include
from django.conf.urls import patterns
from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView
import djcelery.models

from gridplatform.utils.urls import restricted_url


js_info_dict = {
    'packages': (
        'legacy.website',
        'legacy.manage_devices',
        'legacy.manage_customers',
    ),
}


urlpatterns = patterns(
    '',
    (r'^i18n/', include('django.conf.urls.i18n')),
    (r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict),
    (r'^jserror/', include('gridplatform.jserror.urls')),
    url(r'^task_status/$',
        'gridplatform.utils.views.task_status',
        name='task_status'),
    url(r'^manage/customers/', include('legacy.manage_customers.urls')),
    url(r'^manage/agents/', include('legacy.setup_agents.urls')),
    url(r'^locations/', include('legacy.manage_locations.urls')),
    url(r'^groups/', include('legacy.manage_collections.urls')),
    url(r'^devices/', include('legacy.manage_devices.urls')),
    url(r'^measurementpoints/',
        include(
            'legacy.manage_measurementpoints.urls',
            namespace='manage_measurementpoints')),
    url(r'^overview/details/',
        include('legacy.display_measurementpoints.urls')),
    url(r'^overview/indexes/',
        include('legacy.display_indexes.urls')),
    url(r'^projects/', include('legacy.display_projects.urls')),
    url(r'^users/', include('legacy.manage_users.urls')),
    url(r'^widgets/', include('legacy.display_widgets.urls')),
    url(r'^userprofile/', include('legacy.edit_userprofile.urls')),
    url(r'^rules/', include('legacy.manage_rules.urls')),
    url(r'^indexes/', include('legacy.manage_indexes.urls')),
    url(r'^reports/', include('legacy.manage_reports.urls')),
    url(r'', include('legacy.website.urls')),
    url('^energy_use_reports/',
        include('legacy.energy_use_reports.urls')),
    url('^enpi_reports/',
        include('legacy.enpi_reports.urls')),
    url(r'^report_generators/', include('gridplatform.reports.urls')),
    url(r'^project_generators/', include('legacy.projects.urls')),
    url(r'^start/',
        include('energymanager.start_site.urls', namespace='start_site')),
    url(r'^user/', include('gridplatform.users.urls', namespace='users')),
    url(r'^Wibeee/', include('gridplatform.smilics.urls')),
    # Provider site
    restricted_url(
        r'^admin/',
        include('energymanager.provider_site.urls',
                namespace='provider_site'),
        permission='users.access_provider_site',
        requires_provider=True),
    restricted_url(
        r'^configuration/',
        include('energymanager.configuration_site.urls',
                namespace='configuration_site'),
        permission='users.access_provider_site',
        requires_provider=True),
    # LED Light site
    restricted_url(
        r'^led_light/',
        include('energymanager.led_light_site.urls',
                namespace='led_light_site'),
        permission='users.access_led_light_site'),

    # HACK to restrict project urls
    # TODO: Figure out why restricted_url doesn't work in app url files
    restricted_url(
        r'^led_light/',
        include('energymanager.led_light_site.restricted_urls',
                namespace='led_light_site_projects'),
        permission='users.access_led_light_site_projects'),

    # Access price_relay site
    restricted_url(
        r'^price_relay/',
        include('energymanager.price_relay_site.urls',
                namespace='price_relay_site'),
        permission='users.access_price_relay_site'),

    # Project site
    restricted_url(
        r'^escolite/',
        include('energymanager.project_site.urls',
                namespace='project_site'),
        permission='users.access_project_site'),

    # Datahub site
    restricted_url(
        r'^datahub/',
        include('energymanager.datahub_site.urls',
                namespace='datahub_site'),
        permission='users.access_datahub_site'),


    # REST API
    url(r'^api/current/',
        RedirectView.as_view(url=reverse_lazy('api:api-root')),
        name='api-current-version'),
    url(r'^api/v3/', include('gridplatform.api', namespace='api')),

)


admin.autodiscover()

admin.site.unregister(django.contrib.auth.models.User)

admin.site.unregister(djcelery.models.TaskState)
admin.site.unregister(djcelery.models.WorkerState)
admin.site.unregister(djcelery.models.IntervalSchedule)
admin.site.unregister(djcelery.models.CrontabSchedule)
admin.site.unregister(djcelery.models.PeriodicTask)


urlpatterns += patterns(
    '',
    restricted_url(
        r'^sysadmin/',
        include(admin.site.urls),
        requires_is_staff=True),
)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns(
        '',
        url(r'^__debug__/', include(debug_toolbar.urls)),
        url(r'^qunit/', include('django_qunit.urls')),
    )

wifiagent/wifiagent/urls.py
from django.conf.urls import url
#from django.contrib import admin

from wifiagent.relay import views

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'^receiver/$', views.receiver),
]

energymanager/led_light_site/models.py
from django.db import models

# Create your models here.

energymanager/led_light_site/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from __future__ import unicode_literals

import datetime
import calendar

from django.utils.translation import ugettext_lazy as _
from django.utils.translation import ugettext_lazy
from django import forms
from django.core.urlresolvers import reverse
from django.db.models.fields import BLANK_CHOICE_DASH

from gridplatform.utils import generic_views
from gridplatform.utils import units
from gridplatform.utils.breadcrumbs import Breadcrumb
from gridplatform.utils.breadcrumbs import Breadcrumbs
from gridplatform.utils.views import ChooseCustomerBase
from gridplatform.utils.views import CustomerInKwargsMixin
from gridplatform.utils.views import CustomerListMixin
from gridplatform.utils.views import CustomerViewBase
from gridplatform.utils.views import HomeViewBase
from gridplatform.customers.models import Customer
from gridplatform.utils.forms import YearWeekPeriodForm
from gridplatform.utils.forms import this_week_initial_values


from energymanager.energy_projects.models import LedLightProject


class HomeView(HomeViewBase):
    def get_redirect_with_customer_url(self, customer_id):
        return reverse(
            'led_light_site:dashboard',
            kwargs={'customer_id': customer_id})

    def get_choose_customer_url(self):
        return reverse(
            'led_light_site:choose-customer')


class ChooseCustomer(ChooseCustomerBase):
    template_name = 'led_light_site/choose_customer.html'


class CustomerView(CustomerViewBase):
    def get_redirect_with_customer_url(self, customer_id):
        return reverse(
            'led_light_site:dashboard',
            kwargs={'customer_id': customer_id})


class DashboardDetailView(
        CustomerListMixin, generic_views.DetailView):
    model = Customer
    template_name = \
        'led_light_site/dashboard.html'

    def get_breadcrumbs(self):
        return (
            (_('Dashboard'), ''),
        )

    def get_object(self, queryset=None):
        return self.model.objects.get(pk=self.kwargs['customer_id'])

    def get_context_data(self, **kwargs):
        context = super(DashboardDetailView, self).get_context_data(**kwargs)

        projects = self.object.ledlightproject_set.all()
        projects_width_savings = []

        total_saved = None
        total_previous_price = None
        total_led_price = None

        year = int(self.request.GET.get(
            'year', datetime.datetime.today().year))
        month_number = int(self.request.GET.get(
            'month_number', datetime.datetime.today().month))

        from_time = None
        to_time = None

        month_options = (
            '...',
            _('January'),
            _('February'),
            _('March'),
            _('April'),
            _('May'),
            _('June'),
            _('Juli'),
            _('August'),
            _('September'),
            _('October'),
            _('November'),
            _('December'),
        )

        if month_number == 0:
            from_time = datetime.datetime(year, 1, 1, 0, 0, 0).replace(tzinfo=self.object.timezone)
            to_time = datetime.datetime(year + 1, 1, 1, 0, 0, 0).replace(tzinfo=self.object.timezone)
        else:
            from_time = datetime.datetime(year, month_number, 1, 0, 0, 0).replace(tzinfo=self.object.timezone)
            to_time = datetime.datetime(
                year, month_number, calendar.monthrange(
                    year, month_number)[1], 23, 59, 59).replace(tzinfo=self.object.timezone) + datetime.timedelta(
                        seconds=1)

        for project in projects:
            previous_price = project.calculated_previous_price(
                from_time=from_time, to_time=to_time)

            led_price = project.measured_price(
                from_time=from_time, to_time=to_time)

            saved = project.calculate_savings(
                from_time=from_time, to_time=to_time)
            if saved:
                if total_saved:
                    total_saved += saved
                    total_previous_price += previous_price
                    total_led_price += led_price
                else:
                    total_previous_price = previous_price
                    total_led_price = led_price
                    total_saved = saved

                projects_width_savings.append({
                    'name': project.name_plain,
                    'saved': saved,
                    'previous_price': previous_price,
                    'led_price': led_price
                })
            else:
                projects_width_savings.append({
                    'name': project.name_plain,
                    'saved': '-',
                    'previous_price': '-',
                    'led_price': '-'
                })

        context['year'] = year
        context['month_number'] = month_number
        context['month'] = month_options[month_number]
        context['total_saved'] = total_saved
        context['total_previous_price'] = total_previous_price
        context['total_led_price'] = total_led_price
        context['projects'] = projects_width_savings
        context['chart_form'] = YearWeekPeriodForm(
                this_week_initial_values())
        return context


class DashboardBurnDetailView(
        CustomerListMixin, generic_views.DetailView):
    model = Customer
    template_name = \
        'led_light_site/dashboard_burn.html'

    def get_breadcrumbs(self):
        return (
            (_('Dashboard Burn Hours'), ''),
        )

    def get_object(self, queryset=None):
        return self.model.objects.get(pk=self.kwargs['customer_id'])

    def get_context_data(self, **kwargs):
        context = super(
            DashboardBurnDetailView, self).get_context_data(**kwargs)

        projects = self.object.ledlightproject_set.all()
        projects_width_savings = []

        total_burned = None

        year = int(self.request.GET.get(
            'year', datetime.datetime.today().year))
        month_number = int(self.request.GET.get(
            'month_number', datetime.datetime.today().month))

        from_time = None
        to_time = None

        month_options = (
            '...',
            _('January'),
            _('February'),
            _('March'),
            _('April'),
            _('May'),
            _('June'),
            _('Juli'),
            _('August'),
            _('September'),
            _('October'),
            _('November'),
            _('December'),
        )

        if month_number == 0:
            from_time = datetime.datetime(year, 1, 1, 0, 0, 0).replace(
                tzinfo=self.object.timezone)
            to_time = datetime.datetime(year + 1, 1, 1, 0, 0, 0).replace(
                tzinfo=self.object.timezone)
        else:
            from_time = datetime.datetime(
                year, month_number, 1, 0, 0, 0).replace(
                    tzinfo=self.object.timezone)
            to_time = datetime.datetime(
                year, month_number, calendar.monthrange(
                    year, month_number)[1], 23, 59, 59).replace(
                        tzinfo=self.object.timezone) + datetime.timedelta(
                        seconds=1)

        for project in projects:
            burned = project.calculate_burn_hours(
                from_time=from_time, to_time=to_time)

            if burned:
                if total_burned:
                    total_burned += burned
                else:
                    total_burned = burned

                projects_width_savings.append({
                    'name': project.name_plain,
                    'burned': burned,
                })
            else:
                projects_width_savings.append({
                    'name': project.name_plain,
                    'burned': '-',
                })

        context['year'] = year
        context['month_number'] = month_number
        context['month'] = month_options[month_number]
        context['total_burned'] = total_burned
        context['projects'] = projects_width_savings
        return context


class LedLightProjectList(CustomerListMixin, generic_views.TemplateView):
    template_name = 'led_light_site/led_light_project_list.html'

    @staticmethod
    def build_breadcrumbs(customer_id):
        return Breadcrumbs() + Breadcrumb(
            _('Led Light Projects'),
            reverse(
                'led_light_site_projects:led-light-project-list',
                kwargs={'customer_id': customer_id}))

    def get_breadcrumbs(self):
        return self.build_breadcrumbs(self._customer.id)


class LedLightProjectListContentView(
        CustomerListMixin,
        generic_views.ListView):
    search_fields = ['name_plain', ]
    sort_fields = ['name_plain', ]
    model = LedLightProject
    paginate_by = 100
    template_name = 'led_light_site/_led_light_project_list_content.html'


class LedLightProjectForm(forms.ModelForm):

    class Meta:
        model = LedLightProject
        fields = (
            'name', 'previous_tube_count', 'previous_consumption_per_tube',
            'led_tube_count', 'led_consumption_per_tube', 'price',
            'datasource',
        )


class LedLightProjectCreateView(CustomerListMixin,
                                generic_views.CreateView):
    model = LedLightProject
    template_name = 'led_light_site/led_light_project_form.html'
    form_class = LedLightProjectForm

    def form_valid(self, form):
        form.instance.customer_id = self._customer.id
        result = super(LedLightProjectCreateView, self).form_valid(form)
        assert self.object.id
        self._customer.ledlightproject_set.add(self.object)
        return result

    def get_success_url(self):
        return reverse('led_light_site_projects:led-light-project-list',
                       kwargs={'customer_id':
                               self._customer.id})

    def get_cancel_url(self):

energymanager/led_light_site/templates/led_light_site/_led_light_project_list_content.html
{% load i18n %}

{% if object_list %}
<table class="table table-striped table-bordered sorted" data-provides="rowlink">
  <thead>
    <th class="sorting" data-orderby="name_plain">{% trans "Name" %}</th>
  </thead>
  <tbody>
    {% for object in object_list %}
    <tr>
      <td>
        <a href="{% url "led_light_site_projects:led-light-project-update" customer_id=customer.id pk=object.id %}">{{ object.name_plain }}</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% include "bootstrap/_pagination.html" %}
{% else %}
<span>{% trans "No LED light projects present." %}</span>
{% endif %}

energymanager/led_light_site/templates/led_light_site/_menu.html
{% load i18n %}

{% load bootstrap_tags %}

{% if customer %}
<ul class="nav main-menu">
   <li>
    <a href="{% url 'led_light_site:dashboard' customer_id=view.kwargs.customer_id %}">
      {% icon "bar-chart-o" %}<span class="hidden-sm text">{% trans 'Dashboard' %}</span>
    </a>
  </li>
  {% if perms.users.access_led_light_site_projects %}
  <li>
    <a href="{% url 'led_light_site_projects:led-light-project-list' customer_id=view.kwargs.customer_id %}">
      {% icon "gears" %}<span class="hidden-sm text">{% trans 'Projects' %}</span>
    </a>
  </li>
  <li>
    <a href="{% url 'led_light_site_projects:dashboard_burn' customer_id=view.kwargs.customer_id %}">
      {% icon "gears" %}<span class="hidden-sm text">{% trans 'Burn Hours' %}</span>
    </a>
  </li>
  {% endif %}

</ul>
{% endif %}

energymanager/led_light_site/templates/led_light_site/_navbar.html
{% extends "bootstrap/_navbar_base.html" %}

{% load i18n %}
{% load bootstrap_tags %}

{% block home_url %}{% url 'led_light_site:home' %}{% endblock home_url %}
{% block title %}{% trans 'LED Light' %}{% endblock title %}

{% block menu_extra %}
{% include "utils/customer_selection_nav.html" %}
{% endblock menu_extra %}

energymanager/led_light_site/templates/led_light_site/base.html
{% extends "bootstrap/base.html" %}

{% load i18n %}

{% block page_title %}{% trans 'LED Light' %}{% endblock %}

{% block navbar %}
{% include "led_light_site/_navbar.html" %}
{% endblock %}

{% block sidebar %}
{% include "led_light_site/_menu.html" %}
{% endblock %}


{% block page_bottom %}
{% include "utils/customer_selection_modal.html" with urlname='led_light_site:customer' %}
{% endblock page_bottom %}

energymanager/led_light_site/templates/led_light_site/choose_customer.html
{% extends "led_light_site/base.html" %}

{% block page_js %}
<script type="text/javascript">
    jQuery(function() {
        $('#customer-select-modal').modal('show');
    });
</script>
{% endblock page_js %}

energymanager/led_light_site/templates/led_light_site/dashboard.html
{% extends "led_light_site/base.html" %}
{% load i18n %}
{% load l10n %}

{% load bootstrap_tags %}
{% load utils %}

{% block content %}
<div class="light-dashboard">
{% panel _("Total") %}
{% comment %}
<ul class="nav nav-tabs" id="mainCharts">
    <li id="chart24h" class="{% if period == '24h' %}active{% endif %}">
      <a href="{% url 'led_light_site:dashboard' customer_id=view.kwargs.customer_id %}?period=24h">{% trans "24h" %}</a>
    </li>
    
    <li id="chartMonth" class="{% if period == 'month' %}active{% endif %}">
      <a href="{% url 'led_light_site:dashboard' customer_id=view.kwargs.customer_id %}?period=month">{% trans "month" %}</a>
    </li>
    <li id="chartWeek" class="{% if period == 'year' %}active{% endif %}">
      <a href="{% url 'led_light_site:dashboard' customer_id=view.kwargs.customer_id %}?period=year">{% trans "year" %}</a>
    </li>
</ul>
{% endcomment %}
<div class="dropdown pull-right">
  <a href="#" title="{% trans 'Add' %}" class="btn-add" data-toggle="dropdown">
    <span>{% trans 'Month' %}: {{ month }}</span>
  </a>
  <ul class="dropdown-menu">
    <li><a href="{% url 'led_light_site:dashboard' customer_id=view.kwargs.customer_id %}?year={{ year|unlocalize }}&month_number=0">...</a></li>
    <li><a href="{% url 'led_light_site:dashboard' customer_id=view.kwargs.customer_id %}?year={{ year|unlocalize }}&month_number=1">{% trans 'January' %}</a></li>
    <li><a href="{% url 'led_light_site:dashboard' customer_id=view.kwargs.customer_id %}?year={{ year|unlocalize }}&month_number=2">{% trans 'February' %}</a></li>
    <li><a href="{% url 'led_light_site:dashboard' customer_id=view.kwargs.customer_id %}?year={{ year|unlocalize }}&month_number=3">{% trans 'March' %}</a></li>
    <li><a href="{% url 'led_light_site:dashboard' customer_id=view.kwargs.customer_id %}?year={{ year|unlocalize }}&month_number=4">{% trans 'April' %}</a></li>
    <li><a href="{% url 'led_light_site:dashboard' customer_id=view.kwargs.customer_id %}?year={{ year|unlocalize }}&month_number=5">{% trans 'May' %}</a></li>
    <li><a href="{% url 'led_light_site:dashboard' customer_id=view.kwargs.customer_id %}?year={{ year|unlocalize }}&month_number=6">{% trans 'June' %}</a></li>
    <li><a href="{% url 'led_light_site:dashboard' customer_id=view.kwargs.customer_id %}?year={{ year|unlocalize }}&month_number=7">{% trans 'Juli' %}</a></li>
    <li><a href="{% url 'led_light_site:dashboard' customer_id=view.kwargs.customer_id %}?year={{ year|unlocalize }}&month_number=8">{% trans 'August' %}</a></li>
    <li><a href="{% url 'led_light_site:dashboard' customer_id=view.kwargs.customer_id %}?year={{ year|unlocalize }}&month_number=9">{% trans 'September' %}</a></li>
    <li><a href="{% url 'led_light_site:dashboard' customer_id=view.kwargs.customer_id %}?year={{ year|unlocalize }}&month_number=10">{% trans 'October' %}</a></li>
    <li><a href="{% url 'led_light_site:dashboard' customer_id=view.kwargs.customer_id %}?year={{ year|unlocalize }}&month_number=11">{% trans 'November' %}</a></li>
    <li><a href="{% url 'led_light_site:dashboard' customer_id=view.kwargs.customer_id %}?year={{ year|unlocalize }}&month_number=12">{% trans 'December' %}</a></li> 
  </ul>
</div>
<div class="dropdown pull-right">
  <a href="#" title="{% trans 'Add' %}" class="btn-add" data-toggle="dropdown">
    <span>{% trans 'Year' %}: {{ year|unlocalize }}</span>
  </a>
  <ul class="dropdown-menu">
    <li><a href="{% url 'led_light_site:dashboard' customer_id=view.kwargs.customer_id %}?year=2015&month_number={{ month_number|unlocalize }}">2015</a></li>
    <li><a href="{% url 'led_light_site:dashboard' customer_id=view.kwargs.customer_id %}?year=2016&month_number={{ month_number|unlocalize }}">2016</a></li>
    <li><a href="{% url 'led_light_site:dashboard' customer_id=view.kwargs.customer_id %}?year=2017&month_number={{ month_number|unlocalize }}">2017</a></li>
  </ul>
</div>
{% endpanelbuttons %}
<h1>
  <div class="pull-left">
  {% trans 'Saved' %}
  </div>
  <div class="pull-right">
    {% if total_saved %}
    	{{ total_saved|floatformat:2 }}
    {% else %}
    	-
    {% endif %}  DKK
  </div>
</h1>
<div class="clearfix"></div>
<ul class="stats led">
  <li>
    <span>{{ total_previous_price|floatformat:2 }} kr</span>
    <h5>{% trans 'Price with previous tubes' %}</h5>
  </li>
  <li>
    <span>{{ total_led_price|floatformat:2 }} kr</span>
    <h5>{% trans 'Price with LED tubes' %}</h5>
  </li>
</ul>
{% endpanel %}

<div class="info-boxes">
  {% for project in projects %}

  <div class="col-lg-3 col-sm-6 col-xs-6 col-xxs-12">
    <div class="box info-box">
      <div class="backgroundColor darkgreen">
       <div class="clearfix">
          <span class="title">{{ project.name }}</span>
        </div>
        <div class="clearfix">
          <span class="title">{% trans 'Saved' %}</span>
          <span class="value">{{ project.saved|floatformat:2 }} DKK</span>
        </div>
      </div>
      <div class="quarters">
        <div class="quarter q3">
          <div>{{ project.previous_price|floatformat:2 }} DKK <span>{% trans 'Previous Price' %}</span></div>
        </div>
        <div class="quarter q4">
          <div>{{ project.led_price|floatformat:2 }} DKK <span>{% trans 'LED Price' %}</span></div>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
</div>
{% endblock %}

energymanager/led_light_site/templates/led_light_site/led_light_project_form.html
{% extends "led_light_site/base.html" %}
{% load i18n %}
{% load bootstrap_tags %}


{% block content %}
{% panel _("LED Light Project Details") %}
{% bootstrap_form %}
{% form form %}
{% endbootstrap_form %}
{% endpanel %}
{% endblock %}

energymanager/led_light_site/templates/led_light_site/led_light_project_list.html
{% extends "led_light_site/base.html" %}
{% load i18n %}
{% load pagination %}
{% load bootstrap_tags %}

{% block content %}
{% panel _("LED Light Projects") search=True %}
<a href="{% url "led_light_site_projects:led-light-project-create" customer_id=customer.id %}" title="{% trans 'Add' %}">
  {% icon "plus" %}
</a>
{% endpanelbuttons %}
<div class="content-loader" data-url="{% url "led_light_site_projects:led-light-project-list-content" customer_id=customer.id %}" data-orderby="name_plain"></div>
{% endpanel %}

{% endblock %}